pipeline {

    agent {
        label 'docker-worker'
    }

    environment {
        IMAGE_NAME = "easymovies"
        COMPOSE_PROJECT_NAME = "easymovies"
    }

    options {
        timestamps()
    }

    stages {

        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Environment Information') {
            steps {
                sh '''
                    echo "===== Build Environment ====="
                    hostname
                    whoami
                    pwd
                    git --version
                    docker --version
                    docker compose version
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                   docker build -t easymovies:${BUILD_NUMBER} -t easymovies:latest .
                '''
            }
        }

        stage('Run Unit Tests') {
            steps {
                sh '''
                    docker run --rm easymovies:${BUILD_NUMBER} pytest -v
                '''
            }
        }

        stage('Deploy Application') {
            steps {
                sh '''
                    export IMAGE_TAG=${BUILD_NUMBER}
                    export GIT_COMMIT=$(git rev-parse --short HEAD)
                    export BUILD_URL=${BUILD_URL}
                    export BUILD_NUMBER=${BUILD_NUMBER}
                    export GIT_COMMIT=$(git rev-parse --short HEAD)
                    export BUILD_USER=${BUILD_USER_ID:-jenkins}
                    export BUILD_TIME="$(date)"
                    docker compose up -d
                '''
            }
        }

        stage('Smoke Test') {
            steps {
                sh '''
                    echo "Waiting for application..."
                    sleep 10

                    curl --fail http://localhost:5000

                    echo "Smoke test passed."
                '''
            }
        }

        stage('Running Containers') {
            steps {
                sh '''
                    docker ps
                '''
            }
        }
    }

    post {

        always {

            echo "Cleaning up..."

            sh '''
                docker compose down
                docker image prune -f
            '''
        }

        success {
            echo "SUCCESS: EasyMovies deployed successfully."
        }

        failure {
            echo "FAILED: Pipeline execution failed."
        }
    }
}