[jenkins_controller]
jenkins-controller ansible_host=54.211.213.242 ansible_user=ubuntu ansible_ssh_private_key_file=/home/labuser/.ssh/jenkins-ci-generated-key

[jenkins_workers]
jenkins-worker ansible_host=54.173.101.131 ansible_user=ubuntu ansible_ssh_private_key_file=/home/labuser/.ssh/jenkins-ci-generated-key
